export const mockMembers = [
  { id: '1', full_name: 'Admin User', email: 'admin@example.com', gender: 'male', birthdate: '1985-03-15', phone: '+1 234 567 890', address: '123 Main St, New York, NY', join_date: '2023-01-10', status: 'active', hobbies: ['Reading', 'Coding'], notes: 'System administrator.', photo_url: null, role: 'admin' },
  { id: '2', full_name: 'Jane Smith', email: 'jane@example.com', gender: 'female', birthdate: '1990-07-22', phone: '+1 555 123 456', address: '456 Oak Ave, Los Angeles, CA', join_date: '2023-03-05', status: 'active', hobbies: ['Hiking', 'Photography'], notes: 'Active volunteer.', photo_url: null, role: 'editor' },
  { id: '3', full_name: 'Bob Johnson', email: 'bob@example.com', gender: 'male', birthdate: '1978-11-30', phone: '+1 444 987 654', address: '789 Pine Rd, Chicago, IL', join_date: '2023-05-18', status: 'active', hobbies: ['Cooking', 'Cycling'], notes: '', photo_url: null, role: 'member' },
  { id: '4', full_name: 'Maria Garcia', email: 'maria@example.com', gender: 'female', birthdate: '1995-02-14', phone: '+1 333 654 321', address: '321 Elm St, Houston, TX', join_date: '2023-07-01', status: 'pending', hobbies: ['Yoga', 'Painting'], notes: 'Awaiting orientation.', photo_url: null, role: 'member' },
  { id: '5', full_name: 'David Lee', email: 'david@example.com', gender: 'male', birthdate: '1988-09-08', phone: '+1 222 111 333', address: '654 Maple Dr, Phoenix, AZ', join_date: '2022-11-20', status: 'inactive', hobbies: ['Gaming', 'Music'], notes: 'On leave.', photo_url: null, role: 'member' },
  { id: '6', full_name: 'Sarah Wilson', email: 'sarah@example.com', gender: 'female', birthdate: '1992-06-17', phone: '+1 777 888 999', address: '987 Cedar Ln, Philadelphia, PA', join_date: '2024-01-15', status: 'active', hobbies: ['Running', 'Baking'], notes: '', photo_url: null, role: 'member' },
  { id: '7', full_name: 'Tom Brown', email: 'tom@example.com', gender: 'male', birthdate: '1983-04-25', phone: '+1 666 555 444', address: '147 Birch Blvd, San Antonio, TX', join_date: '2023-09-12', status: 'active', hobbies: ['Football', 'Woodworking'], notes: 'Treasurer.', photo_url: null, role: 'member' },
]
